### ISSUE TITLE
possible issue with dynamic_cast<Piece *>

### ISSUE THREAD

**Issue by vbokser** [MakeSchool-Tutorials/Sushi-Neko-CocosStudio-Cpp#3]
I keep getting a Null return for the dynamic_cast<Piece *> when in the for loop for making the the 10 pieces.

I used a static_cast<Piece *> instead and that worked. Is this an issue with using dynamic_cast in this location of the code?

New to cocos2d-x so not sure if this a real issue. thnx

**Comment by vbokser** [comment]
my bad of course figured out a simple typo in the code.

**Comment by danielhaaser** [comment]
No worries, thanks for the update!
